# Generated by Django 5.0.3 on 2024-03-17 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_table_alter_category_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PLACED', 'PLACED'), ('DISPACTCHED', 'DISPACTCHED'), ('DELIVERED', 'DELIVERED')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INPROGRESS', 'INPROGRESS'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'payment_status',
            },
        ),
        migrations.RenameField(
            model_name='address',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='sub_category_id',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='productcombination',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='product_combination_id',
            new_name='product_combination',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='variationclass',
            old_name='variation_type_id',
            new_name='variation_type',
        ),
        migrations.RenameField(
            model_name='variationcombination',
            old_name='product_combination_id',
            new_name='product_combination',
        ),
        migrations.RenameField(
            model_name='variationtype',
            old_name='sub_category_id',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variationcombination',
            name='variation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.variationclass'),
        ),
        migrations.AddField(
            model_name='variationcombination',
            name='variation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.variationtype'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopping_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shoppingcart')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentmethod')),
                ('payment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentstatus')),
            ],
            options={
                'db_table': 'payment_detail',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productitem')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shoppingcart')),
            ],
            options={
                'db_table': 'shopping_cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.orderstatus')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentdetail')),
                ('shopping_cart_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shoppingcartitem')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Very Good')], default=0)),
                ('comment', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_review',
            },
        ),
        migrations.CreateModel(
            name='WishlistTub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist_tub',
            },
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productitem')),
                ('wishlist_tub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wishlisttub')),
            ],
            options={
                'db_table': 'wishlist_item',
            },
        ),
    ]
