# Generated by Django 5.0.3 on 2024-03-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orderstatus_paymentmethod_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Order Status', 'verbose_name_plural': 'Order Statuses'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetail',
            options={'verbose_name': 'Payment Detail', 'verbose_name_plural': 'Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name': 'Payment Status', 'verbose_name_plural': 'Payment Statuses'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productcombination',
            options={'verbose_name': 'Product Combination', 'verbose_name_plural': 'Product Combinations'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'Product Item', 'verbose_name_plural': 'Product Items'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Shopping Cart', 'verbose_name_plural': 'Shopping Carts'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartitem',
            options={'verbose_name': 'Shopping Cart Item', 'verbose_name_plural': 'Shopping Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='userreview',
            options={'verbose_name': 'User Review', 'verbose_name_plural': 'User Reviews'},
        ),
        migrations.AlterModelOptions(
            name='variationclass',
            options={'verbose_name': 'Variation Class', 'verbose_name_plural': 'Variation Classes'},
        ),
        migrations.AlterModelOptions(
            name='variationcombination',
            options={'verbose_name': 'Variation Combination', 'verbose_name_plural': 'Variation Combinations'},
        ),
        migrations.AlterModelOptions(
            name='variationtype',
            options={'verbose_name': 'Variation Type', 'verbose_name_plural': 'Variation Types'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Wishlist Item', 'verbose_name_plural': 'Wishlist Items'},
        ),
        migrations.AlterModelOptions(
            name='wishlisttub',
            options={'verbose_name': 'Wishlist Tub', 'verbose_name_plural': 'Wishlist Tubs'},
        ),
        migrations.AlterField(
            model_name='productcombination',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
