# Generated by Django 5.0.3 on 2024-03-25 11:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_productitem_product_combination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variationcombination',
            name='variation_type',
        ),
        migrations.AddField(
            model_name='userreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='variation_combination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.variationcombination'),
        ),
        migrations.AlterUniqueTogether(
            name='variationclass',
            unique_together={('variation_type', 'value')},
        ),
    ]
